name=Boardoza L9110S Dual-Channel Motor Driver
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza L9110S Dual-Channel H-Bridge Motor Driver
paragraph=This library provides an easy-to-use interface for controlling DC motors and 4-wire stepper motors using the L9110S dual-channel driver. It supports independent speed control via PWM, direction switching (forward/reverse), and braking for İki separate motors. With its lightweight footprint and intuitive API, it is ideal for DIY robotics, small RC vehicles, and any project requiring simple yet effective motor management on Arduino or PlatformIO platforms.
category=Device Control
url=https://github.com/Boardoza/Boardoza_L9110S_Dual_DC_Motor_Driver_Breakout_Board
architectures=*